# Generated by Django 5.2.12 on 2026-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('dispatcher', 'Dispatcher'), ('driver', 'Driver'), ('customer', 'Customer')], default='driver', max_length=20),
        ),
    ]
